import { Task, RamadanDay } from './types';

export const TASKS: Task[] = [
  { id: 1, title: 'تلاوت قرآن (جزء روز)', url: 'https://tanzil.net', icon: '📖' },
  { id: 2, title: 'نماز شب', url: 'https://erfan.ir/farsi/35798.html', icon: '🌙' },
  { id: 3, title: 'سوره قدر (افطار و سحر)', url: 'https://tanzil.net/#97:1', icon: '✨' },
  { id: 4, title: 'دعای افطار و امام زمان', url: 'https://erfan.ir/farsi/35799.html', icon: '🤲' },
  { id: 5, title: 'مواسات و همدلی', description: 'افطاری دادن و کمک به مستضعفین', icon: '🤝' },
  { id: 6, title: 'غسل شب‌های فرد', description: 'غسل مستحبی شب‌های فرد ماه رمضان', icon: '💧' },
  { id: 7, title: 'دعای افتتاح', url: 'https://erfan.ir/farsi/35802.html', icon: '📜' },
  { id: 8, title: 'دعای ابوحمزه ثمالی', url: 'https://erfan.ir/farsi/35803.html', icon: '⚖️' },
  { id: 9, title: 'کثرت صلوات', icon: '📿' },
  { id: 10, title: 'دعاهای بعد از نماز', url: 'https://erfan.ir/farsi/35804.html', icon: '🕌' },
  { id: 11, title: 'نماز ماه رمضان', icon: '🛐' },
  { id: 12, title: 'سوره دخان', url: 'https://tanzil.net/#44:1', icon: '🗞️' },
  { id: 13, title: 'اعمال صبح و شام', icon: '☀️' },
  { id: 14, title: 'صدقه روزانه', url: 'https://payping.ir/d/jGLa', icon: '🪙' },
];

export const RAMADAN_DAYS: RamadanDay[] = [
  { dayIndex: 1, weekday: 'پنجشنبه', hijriDate: 1, solarDate: '30 بهمن' },
  { dayIndex: 2, weekday: 'جمعه', hijriDate: 2, solarDate: '1 اسفند' },
  { dayIndex: 3, weekday: 'شنبه', hijriDate: 3, solarDate: '2 اسفند' },
  { dayIndex: 4, weekday: 'یکشنبه', hijriDate: 4, solarDate: '3 اسفند' },
  { dayIndex: 5, weekday: 'دوشنبه', hijriDate: 5, solarDate: '4 اسفند' },
  { dayIndex: 6, weekday: 'سه‌شنبه', hijriDate: 6, solarDate: '5 اسفند' },
  { dayIndex: 7, weekday: 'چهارشنبه', hijriDate: 7, solarDate: '6 اسفند', event: 'رحلت حضرت ابوطالب (ع)' },
  { dayIndex: 8, weekday: 'پنجشنبه', hijriDate: 8, solarDate: '7 اسفند' },
  { dayIndex: 9, weekday: 'جمعه', hijriDate: 9, solarDate: '8 اسفند' },
  { dayIndex: 10, weekday: 'شنبه', hijriDate: 10, solarDate: '9 اسفند', event: 'رحلت حضرت خدیجه (س)' },
  { dayIndex: 11, weekday: 'یکشنبه', hijriDate: 11, solarDate: '10 اسفند' },
  { dayIndex: 12, weekday: 'دوشنبه', hijriDate: 12, solarDate: '11 اسفند' },
  { dayIndex: 13, weekday: 'سه‌شنبه', hijriDate: 13, solarDate: '12 اسفند' },
  { dayIndex: 14, weekday: 'چهارشنبه', hijriDate: 14, solarDate: '13 اسفند' },
  { dayIndex: 15, weekday: 'پنجشنبه', hijriDate: 15, solarDate: '14 اسفند', event: 'ولادت امام حسن مجتبی (ع)' },
  { dayIndex: 16, weekday: 'جمعه', hijriDate: 16, solarDate: '15 اسفند' },
  { dayIndex: 17, weekday: 'شنبه', hijriDate: 17, solarDate: '16 اسفند' },
  { dayIndex: 18, weekday: 'یکشنبه', hijriDate: 18, solarDate: '17 اسفند' },
  { dayIndex: 19, weekday: 'دوشنبه', hijriDate: 19, solarDate: '18 اسفند', event: 'ضربت خوردن امام علی (ع)' },
  { dayIndex: 20, weekday: 'سه‌شنبه', hijriDate: 20, solarDate: '19 اسفند' },
  { dayIndex: 21, weekday: 'چهارشنبه', hijriDate: 21, solarDate: '20 اسفند', event: 'شهادت حضرت امیرالمؤمنین (ع)' },
  { dayIndex: 22, weekday: 'پنجشنبه', hijriDate: 22, solarDate: '21 اسفند' },
  { dayIndex: 23, weekday: 'جمعه', hijriDate: 23, solarDate: '22 اسفند', event: 'شب بیست و سوم و روز قدس' },
  { dayIndex: 24, weekday: 'شنبه', hijriDate: 24, solarDate: '23 اسفند' },
  { dayIndex: 25, weekday: 'یکشنبه', hijriDate: 25, solarDate: '24 اسفند' },
  { dayIndex: 26, weekday: 'دوشنبه', hijriDate: 26, solarDate: '25 اسفند' },
  { dayIndex: 27, weekday: 'سه‌شنبه', hijriDate: 27, solarDate: '26 اسفند' },
  { dayIndex: 28, weekday: 'چهارشنبه', hijriDate: 28, solarDate: '27 اسفند' },
  { dayIndex: 29, weekday: 'پنجشنبه', hijriDate: 29, solarDate: '28 اسفند' },
  { dayIndex: 30, weekday: 'جمعه', hijriDate: 30, solarDate: '29 اسفند' },
];
